### ISSUE TITLE
Error Message in Dash by running example Code usage.py

### ISSUE THREAD

**Issue by Marlensche** [danielTobon43/update-trace-dash-plotly#3]
Dear @danielTobon43 
I tried to run the code from usage.py (exactly the same) and in Dash it always come the error:

"TypeError: Cannot read property 'length' of undefined

    at i.value (http://127.0.0.1:8050/_dash-component-suites/dash_update_data_components/dash_update_data_components.v0_0_1m1611318388.min.js:1:2961)

    at finishClassComponent (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:17319:33)

    at updateClassComponent (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:17269:26)

    at beginWork (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:18788:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:286:33)

    at beginWork$1 (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:23369:9)

    at performUnitOfWork (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:22323:14)

    at workLoopSync (http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_8_1m1600773499.13.0.js:22296:24)"

I'm not sure what I did wrong here so maybe you can help me with this?

Thank you very much :)

**Comment by ghost** [comment]
Hi @Marlensche I think the problem is related to the version of your dash, I just tried the code and it works on:

plotly 4.8.1
Dash 1.4.1

You can install a specific dash version with:

`pip install dash==1.4.1`

This will update your current version to 1.4.1 even if you have the latest version.

I hope this helps.

**Comment by Marlensche** [comment]
Hi @danielTobon43 

Yes with dash == 1.4.1 the example works. 
Unfortunately other code won't work then - do you have in mind to update your code to a later version of dash? :)

Lg, Marlene

**Comment by ghost** [comment]
Hi @Marlensche.

The main source code of this project is from this guy: [mydcc]( https://github.com/jimmybow/mydcc) I think you could ask him if he will develop a new version for the latest dash version. I personally don't use javascript so I can't help you with a new version of this software. 

What I can suggest to you is 2 things: 

1. find a new dash component from another guy for your project for a newer dash version
2. create your own dash component following the steps in https://dash.plotly.com/plugins

I hope this helps with your project!

Daniel
